//
//  CourseListPresenter.swift
//  CleanSwiftCourses
//
//  Created by Дарья Кобелева on 06.08.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseListPresentationLogic {
    func presentSomething(response: CourseList.Something.Response)
}

class CourseListPresenter: CourseListPresentationLogic {
    
    weak var viewController: CourseListDisplayLogic?
    
    func presentSomething(response: CourseList.Something.Response) {
        let viewModel = CourseList.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
