//
//  CourseDetailsInteractor.swift
//  CleanSwiftCourses
//
//  Created by Дарья Кобелева on 06.08.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseDetailsBusinessLogic {
    func doSomething(request: CourseDetails.Something.Request)
}

protocol CourseDetailsDataStore {
    
}

class CourseDetailsInteractor: CourseDetailsBusinessLogic, CourseDetailsDataStore {
    
    var presenter: CourseDetailsPresentationLogic?
    var worker: CourseDetailsWorker?
    
    func doSomething(request: CourseDetails.Something.Request) {
        worker = CourseDetailsWorker()
        worker?.doSomeWork()
        
        let response = CourseDetails.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
